spring:
  application:
    name: api-gateway

server:
  port: 4444



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
    register-with-eureka: true



#zuul:
#  routes:
#    springboot: /springboot/**
#  ignored-services: feign-consumer
#      path: /springboot/**
#      serviceId: springboot

#springboot:
#  ribbon:
#    listOfServers: http://localhost:8081/,http://localhost:8082/  传统方式配置
zuul:
  routes:
    springboot: /springboot/**
  prefix: /springboot
  retryable: false



hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 4000