server:
  port: 8888



spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: springcloud
    password: springcloud
  application:
    name: stream-hello
  cloud:
    stream:
      bindings:
        input:
          destination: common-topic
          group: stream-hello
        output:
          destination: common-topic

logging:
  level:
    com.myself.streamhello: debug