spring:
  application:
    name: ribbon-consumer
  sleuth:
    sampler:
      probability: 1

server:
  port: 2222

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

