spring:
  application:
    name: ribbon-consumer
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: web

server:
  port: 2222

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

