spring:
  output:
    ansi:
      enabled: detect
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    maxIdle: 300
    maxTotal: 1000
    maxWaitMillis: 1000
    minEvictableIdleTimeMillis: 300000
    numTestsPerEvictionRun: 1024
    timeBetweenEvictionRunsMillis: 30000
    testOnBorrow: true
    testWhileIdle: true
    timeout: 6000
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false


logging:
  file: E:/logs/study.log
  level:
    com.myself: debug

mybatis:
  mapper-locations: classpath:mapper/*.xml
